### PR TITLE
Drop Node.js 6, modernize code, return Promise from async function

### LINKED ISSUE #33: Return a promise
Since the library is already written with promises, it'd be nice if it could return a promise. I generally prefer promises over callbacks, because they're really nice to work with in conjunction with `async function`s 😋

### PR DESCRIPTION
**Pull request by coreyfarrell**
* Implement with async functions
* Use util.promisify
* Replace `var` with `const` or `let`
* Use arrow functions for callbacks
* Update Travis testing matrix

Fixes #33

### CODE REVIEW

**Comment by isaacs** [comment]
This is great!  Unfortunately, I landed a few PRs before getting to this one, and it's full of merge conflicts.

Would you mind terribly rebasing onto latest master?  If that's too much of a pita, I can port it myself pretty soon.

**Comment by coreyfarrell** [comment]
I can probably rebase tomorrow.  Could you please look at https://github.com/npm/write-file-atomic/issues/33#issuecomment-494389147 let me know what you think about the `Promise` option?

**Comment by isaacs** [comment]
Go ahead and drop it in the next semver major.  Just use and return native promises.

**Comment by coreyfarrell** [comment]
OK rebase is done.

One note, the code to get `tmpfile` into the callback is a little odd now that we the async work is done in a separate function.  Would it make sense to have a callback option for reporting creation of the `tmpfile`:
```js
if (options.tmpfileCreated) {
  options.tmpfileCreated(tmpfile)
}
```

This would allow `tmpfileCreated` to be reported as soon as it's created rather than waiting until completion.  It would also allow the sync method to report `tmpfile` even if a failure occurred after the tmpfile was created.

CC @novemberborn

**Comment by isaacs** [comment]
So far, temp file reporting has never been published in a release, so from my pov, we're free to implement it however.  Reporting what temp file was created after it's already been deleted is definitely a bit strange.

Yes, a callback option here makes more sense, imo.  Let's get that in and then cut a v3 release.

**Pull request merged**
