### PR TITLE
Fix FD leak in writeFileAsync() (fixes #52)

### LINKED ISSUE #52: FD leak on every successful writeFileAsync()
In v3.0.0, the async version calls `close()` only in `finally` but by that time `fd` is already [set to null](https://github.com/npm/write-file-atomic/blob/master/index.js#L106) unless there was an error, so `fd` leaks on every successful call.

### PR DESCRIPTION
**Pull request by MartinKolarik**

### CODE REVIEW

**Comment by shane-axiom** [comment]
@issacs this is biting us, taking up hundreds of GBs of disk space with leaked, deleted file handled. Any chance of merge & release?

**Comment by isaacs** [comment]
Since the `fs.close` is being called in the `finally` block, couldn't we just remove the `fd = null` on line 106?  It looks like that's the obvious error.

**Comment by isaacs** [comment]
It's not a good idea to ignore errors from `close(2)`, as it can sometimes indicate a legitimate problem.

Also, a test for this uncovered a few other cases where closes weren't matched to opens.

Fixed on 3.0.1, slightly differently from this patch.  Thanks for pointing it out!

**Comment by shane-axiom** [comment]
Thank you both!

**Pull request closed without merging**
